Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'webserver_apache'

## Configurações de rede:

# Porta 80 da máquina virtual para a porta 8080 da máquina local:
  config.vm.network "forwarded_port", guest: 80, host: 8080 # apache/nginx
  
# Interface de rede privada com endereço IP estático:
  config.vm.network "private_network", type: "static", ip: '192.168.10.10'
  config.vm.network "public_network", type: "dhcp"

# Configurações do provedor:
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'webserver_apache'
    vb.cpus = '2'
    vb.memory = '1024'
  end
  
# Configurações do diretório Compartilhado:
config.vm.synced_folder "./shared_windows", "/shared_linux" # do host(shared_windows) para o virtual(shared_linux)

# Configurações de Shell:
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y htop
    apt-get install -y nano
    apt-get install -y python3
    apt-get install -y apache2
    ufw allow 8080/tcp
    systemctl start apache2
    systemctl enable apache2
    apt-get install -y curl
    curl -fsSL https://get.docker.com | sh
  SHELL
  
end